name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-publish-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore, build and publish
      run: cd DiscordGitToolbox.App/ && dotnet publish -c Release -o out

  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload the project + built assemblies
      uses: actions/upload-artifact@v1
      with:
        name: project-with-built-assemblies
        path: .

  test:
    runs-on: ubuntu-latest
    needs: build-debug
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get the project + built assemblies
      uses: actions/download-artifact@v1
      with:
        name: project-with-built-assemblies
        path: .
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test --no-restore --no-build --verbosity normal --logger GitHubActions
