name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload the built assemblies
      uses: actions/upload-artifact@v1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get the built assemblies
      uses: actions/download-artifact@v1
    - name: Test
      run: dotnet test --no-restore --verbosity normal
